version: "3.9"
services:
  db:
    env_file: ./.envs/.local/.postgres

  api:
    build: ./api/
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --no-input && ./manage.py runserver 0.0.0.0:8000",
      ]
    env_file:
      - ./.envs/.local/.api
